# Generated by Django 3.2.20 on 2023-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('new_price', models.PositiveIntegerField(null=True)),
                ('old_price', models.PositiveIntegerField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('product_code', models.PositiveIntegerField()),
            ],
        ),
    ]
